spring.application.name=user_service

app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration-ms=${ACCESS_TOKEN_EXP:900000}
app.jwt.refresh-token-expiration-ms=${REFRESH_TOKEN_EXP:604800000}

app.cache.default-ttl-minutes: ${CACHE_DEFAULT_TTL_MINUTES:10}

app.kafka.topics.user-registered: user.registered
app.kafka.topics.password-reset-requested: user.password-reset-requested
app.kafka.topics.password-changed: user.password-changed
app.kafka.topics.payment-completed: payment.completed

server.port: ${SERVER_PORT:8081}
server.error.include-message: never
server.error.include-stacktrace: never

logging.level.com.ticks.user-service: INFO
logging.level.org.springframework.cache: DEBUG
logging.level.org.springframework.security: WARN
logging.level.org.hibernate.SQL: WARN

spring.datasource.url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_service_db}}
spring.datasource.username: ${DB_USER:postgres}
spring.datasource.password: ${DB_PASSWORD:postgres}
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size: 10
spring.datasource.hikari.minimum-idle: 2
spring.datasource.hikari.connection-timeout: 30000
spring.datasource.hikari.idle-timeout: 600000
spring.datasource.hikari.max-lifetime: 1800000

spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format-sql: true
spring.jpa.properties.hibernate.default-schema: public

# Redis
spring.data.redis.host: ${REDIS_HOST:localhost}
spring.data.redis.port: ${REDIS_PORT:6379}
spring.data.redis.password: ${REDIS_PASSWORD:}
spring.data.redis.timeout: 2000ms
spring.data.redis.lettuce.pool.max-active: 8
spring.data.redis.lettuce.pool.max-idle: 4
spring.data.redis.lettuce.pool.min-idle: 1
spring.data.redis.lettuce.pool.max-wait: 1000ms

spring.cache.type: redis
spring.cache.redis.time-to-live: 600000
spring.cache.redis.cache-null-values: false
spring.cache.redis.use-key-prefix: true
spring.cache.redis.key-prefix: "user-svc::"

# Kafka
spring.kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers: false
spring.kafka.consumer.group-id: user-service-group
spring.kafka.consumer.auto-offset-reset: earliest
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages: "com.ticks.*,java.util"
spring.kafka.consumer.properties.spring.json.use.type.headers: false
spring.kafka.consumer.properties.spring.json.value.default.type: java.util.Map
